### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open-pension-net-scraper#1]
- Create a `README.md` file.
- Create a `.gitignore` file.
- Create a `.travis.yml` file.

Link to the example repo: https://github.com/nirgn975/open_pension_scraper

**Comment by uda** [comment]
miscellaneous?

**Comment by nirgn975** [comment]
@uda Yeah, didn't know how to call it.
As you can see It's all sort of thing that not related to each other, just to get this repo of the ground. If you have a better name edit it (;
